# Generated by Django 3.0.4 on 2023-03-13 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='ticketId',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='quantity',
        ),
    ]
